[package]
name = "nmstate-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"


[dependencies]
clap = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
env_logger = { workspace = true, optional = true }
log = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, features = ["signal"] }
uuid = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
nispor = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
nmstate = { path = "../lib", default-features = false }
serde_yaml = { workspace = true }
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"
